apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-pvc
  namespace: n8n
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "local-path"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
  namespace: n8n
spec:
  selector:
    app: chromadb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb-deployment
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: chromadb/chroma:0.5.5
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: chromadb-data
          mountPath: /chroma/chroma
      volumes:
      - name: chromadb-data
        persistentVolumeClaim:
          claimName: chromadb-pvc
